
# Setup test modules
# needs:
#   name
#   function
#   parameters (optional)
#   selected_outputs (optional)
#   rename_outputs (optional)

modules:
  - name: "Loading"
    function: loading
    selected_outputs:
      - mol_pred_loaded
      - mol_true_loaded
      - mol_cond_loaded
    rename_outputs:
      mol_pred_loaded: "Docked ligand successfully loaded"
      mol_true_loaded: "Crystal ligand successfully loaded"
      mol_cond_loaded: "Crystal protein successfully loaded"
  - name: "Chemistry"
    function: sanity
    selected_outputs:
      - chemically_valid
    rename_outputs:
      chemically_valid: "Predicted molecule chemically valid"
  - name: "Chemistry"
    function: identity
    parameters:
      inchi_options: "w" # options passed to InChI generation
    selected_outputs:
      - formula
      - connections
      - stereo
    rename_outputs:
      formula: "Molecular formula preserved"
      connections: "Molecular bonds preserved"
      stereo: "Stereochemistry preserved"
  - name: "Geometry"
    function: "distance_geometry"
    parameters:
      bound_matrix_params:
        set15bounds: True # topology based bounds also for 1,5- not just until 1,4-
        scaleVDW: True # scale down lower bounds for atoms less than 5 bonds apart
        doTriangleSmoothing: True
        useMacrocycle14config: False
      threshold_bad_bond_length: 0.2 # widens DG bound by this factor
      threshold_bad_angle: 0.2 # widens DG bound by this factor
      threshold_clash: 0.2 # widens DG bound by this factor
      ignore_hydrogens: True # ignore hydrogens
    selected_outputs:
      - bond_lengths_within_bounds
      - bond_angles_within_bounds
      - no_internal_clash
    rename_outputs:
      bond_lengths_within_bounds: "Bond lengths within bounds"
      bond_angles_within_bounds: "Bond angles within bounds"
      no_internal_clash: "No internal clashes"
  - name: "Flatness"
    function: "flatness"
    parameters:
      flat_systems: # list atoms which together should lie on plane as SMARTS matches
        aromatic_5_membered_rings_sp2: "[ar5^2]1[ar5^2][ar5^2][ar5^2][ar5^2]1"
        aromatic_6_membered_rings_sp2: "[ar6^2]1[ar6^2][ar6^2][ar6^2][ar6^2][ar6^2]1"
        # - trigonal_planar_double_bonds: "[#6;X3;D2,D3;^2]=[#6;X3;D2,D3;^2]"
      threshold_flatness: 0.1 # max distance in A to closest shared plane
    selected_outputs:
      - flatness_passes
    rename_outputs:
      flatness_passes: "Flatness passes"
  - name: "Energy ratio"
    function: energy_ratio
    parameters:
      threshold_energy_ratio: 7.0
      ensemble_number_conformations: 50
    selected_outputs:
      - energy_ratio_passes
    rename_outputs:
      energy_ratio_passes: "Energy ratio passes"
  - name: "Distance to protein"
    function: "intermolecular_distance"
    parameters:
      vdw_scale: 0.8
      clash_cutoff: 0.05
      ignore_hydrogens: True
      ignore_types:
      - organic_cofactors
      - inorganic_cofactors
      max_distance: 5.0
    selected_outputs:
      - not_too_far_away
      - no_clashes
    rename_outputs:
      not_too_far_away: "Not too far away"
      no_clashes: "No clashes with protein"
  - name: "Distance to organic cofactors"
    function: "intermolecular_distance"
    parameters:
      vdw_scale: 0.8
      clash_cutoff: 0.05
      ignore_hydrogens: True
      ignore_types:
      - protein
      - inorganic_cofactors
      max_distance: 5.0
    selected_outputs:
      - no_clashes
    rename_outputs:
      no_clashes: "No clashes with organic cofactors"
  - name: "Distance to inorganic cofactors"
    function: "intermolecular_distance"
    parameters:
      vdw_scale: 0.8
      clash_cutoff: 0.05
      ignore_hydrogens: True
      ignore_types:
      - protein
      - organic_cofactors
      max_distance: 5.0
    selected_outputs:
      - no_clashes
    rename_outputs:
      no_clashes: "No clashes with inorganic cofactors"
  - name: "Volume overlap with protein"
    function: volume_overlap
    parameters:
      clash_cutoff: 0.05
      vdw_scale: 0.8
      ignore_hydrogens: True
      ignore_types:
      - organic_cofactors
      - inorganic_cofactors
    selected_outputs:
      - no_volume_clash
    rename_outputs:
      volume_overlap: "Volume overlap with protein"
      no_volume_clash: "No volume clash with protein"
  - name: "Volume overlap with organic cofactors"
    function: volume_overlap
    parameters:
      clash_cutoff: 0.05
      vdw_scale: 0.8
      ignore_hydrogens: True
      ignore_types:
      - protein
      - inorganic_cofactors
    selected_outputs:
      - no_volume_clash
    rename_outputs:
      volume_overlap: "Volume overlap with organic cofactors"
      no_volume_clash: "No volume clash with organic cofactors"
  - name: "Volume overlap with inorganic cofactors"
    function: volume_overlap
    parameters:
      clash_cutoff: 0.05
      vdw_scale: 0.8
      ignore_hydrogens: True
      ignore_types:
      - protein
      - organic_cofactors
    selected_outputs:
      - no_volume_clash
    rename_outputs:
      volume_overlap: "Volume overlap with inorganic cofactors"
      no_volume_clash: "No volume clash with inorganic cofactors"
  - name: "RMSD"
    function: rmsd
    parameters:
      rmsd_threshold: 2.0
    selected_outputs:
      - rmsd_within_threshold
    rename_outputs:
      rmsd_within_threshold: "RMSD within threshold"

# Options for loading molecule files with RDKit
loading:
  mol_pred:
    cleanup: False
    sanitize: False
    add_hs: False
    assign_stereo: False
    load_all: True
  mol_True:
    cleanup: False
    sanitize: False
    add_hs: False
    assign_stereo: False
    load_all: True
  mol_cond:
    cleanup: False
    sanitize: False
    add_hs: False
    assign_stereo: False
    proximityBonding: False
