version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  jobs:
    pre_install:
      - pip install dependency-groups
      - dependency-groups docs > docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .

formats:
  - htmlzip
  - pdf
  - epub
