name: Publishing

on:
  release:
    types: [created]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout source
      uses: actions/checkout@v3


    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flit

    - name: Build and publish
      env:
        FLIT_USERNAME: __token__
        FLIT_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        FLIT_INDEX_URL: https://test.pypi.org/legacy/
      run: |
        flit publish
