name: Validation

on: [pull_request, workflow_dispatch]

jobs:
  validation:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout source
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit

    - name: Cache for pre-commit
      id: cache-pre-commit
      uses: actions/cache@v3
      env:
        cache-name: pre-commit-environment
      with:
        # pre-commit cache files are stored in `~/.cache/pre-commit` by default
        path: ~/.cache/pre-commit
        key: ${{ runner.os }}_${{ env.cache-name }}
        restore-keys: |
          - ${{ runner.os }}_${{ env.cache-name }}
          - ${{ env.cache-name }}


    - name: Run pre-commit hooks
      run: pre-commit run --all-files --show-diff-on-failure --color=always
