name: Validation

on: [pull_request, workflow_dispatch]

permissions:
  contents: read
  pull-requests: read

jobs:
  validation:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.13"]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Cache for pre-commit
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pre-commit-

      - name: Install dependencies
        run: |
          uv sync --group dev --group test

      - name: Run pre-commit hooks
        run: uv run pre-commit run --all-files --show-diff-on-failure --color=always

      - name: Summary
        if: always()
        run: echo "Pre-commit validation completed for Python ${{ matrix.python-version }}"
